/**
 * Created by vitalii.kyktov on 3/10/17.
 */

export const CONTACTS_START_FETCHING = 'CONTACTS_START_FETCHING';
export const CONTACTS_FINISH_FETCHING = 'CONTACTS_FINISH_FETCHING';

export const POSITION_START_FETCHING = 'POSITION_START_FETCHING';
export const POSITION_FINISH_FETCHING = 'POSITION_FINISH_FETCHING';
export const SET_CURRENT_DATE = 'SET_CURRENT_DATE';


export const SET_BIRTHDAY_DATE = 'SET_BIRTHDAY_DATE';
export const SET_BIRTHDAY_TIME = 'SET_BIRTHDAY_TIME';
export const SET_BIRTHDAY_LOCATION = 'SET_BIRTHDAY_LOCATION';

